### ISSUE TITLE
Mongoose error on set up

### ISSUE THREAD

**Issue by prondubuisi** [dscimsu/resultTracker#68]
```
/home/prondubuisi/gitrepos/resultt/node_modules/mongoose/lib/connection.js:541
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^
Error [MongooseError]: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at new MongooseError (/home/prondubuisi/gitrepos/resultt/node_modules/mongoose/lib/error/mongooseError.js:10:11)
    at NativeConnection.Connection.openUri (/home/prondubuisi/gitrepos/resultt/node_modules/mongoose/lib/connection.js:541:11)
    at Mongoose.connect (/home/prondubuisi/gitrepos/resultt/node_modules/mongoose/lib/index.js:328:15)
    at Object.<anonymous> (/home/prondubuisi/gitrepos/resultt/app.js:28:10)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/prondubuisi/gitrepos/resultt/bin/www:7:11)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  message: 'The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.',
  name: 'MongooseError'
}
[nodemon] app crashed - waiting for file changes before starting...

```

Hello @rexsteroxy  the readme does not describe how to set up a database

**Comment by rexsteroxy** [comment]
I have updated the readMe with the database setup instruction. Try it out and let me know if it works for you.
